name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: jchilders

jobs:
  Lint-Test-Build:
    runs-on: ubuntu-latest
    env:
      TURBO_CACHE_KEY: ${{ matrix.os }}-${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm turbo run check --output-logs=new-only
      - run: pnpm turbo run lint --output-logs=new-only
      - run: pnpm turbo run test --output-logs=new-only -- --coverage
      - run: pnpm turbo run build --output-logs=new-only
