Defaults: &defaults
  - uses: actions/checkout@v2
  - uses: pnpm/action-setup@v2.0.1
    with:
      version: 6.32.9
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: 16.15.0
  - run: pnpm install --frozen-lockfile
  - uses: actions/cache@v2
    with:
      path: ${{ github.workspace }}/node_modules
      key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
      restore-keys: |
        ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}-

name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps: *defaults
  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps: &defaults
      - run: pnpm test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps: &defaults
      - run: DOCKER_BUILDKIT=1 pnpm docker
