name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PNPM_VERSION: 7.1.6
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: jchilders

jobs:
  Lint-Test-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm turbo run lint test build --output-logs=new-only