name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - run: pnpm test
