name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      
      - name: Get turbo store directory
        id: turbo-cache
        run: |
          echo "::set-output name=turbo_cache_dir::./node_modules/.cache/turbo"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/cache@v3
        name: Setup turbo cache
        with:
          path: ${{ steps.turbo-cache.outputs.turbo_cache_dir }}
          key: ${{ runner.os }}-turbo-store-${{ hashFiles(steps.turbo-cache.outputs.turbo_cache_dir) }}-${{ hashFiles('**/turbo.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-store-${{ hashFiles(steps.turbo-cache.outputs.turbo_cache_dir) }}-${{ hashFiles('**/turbo.json') }}
            ${{ runner.os }}-turbo-store-${{ hashFiles(steps.turbo-cache.outputs.turbo_cache_dir) }}-
            ${{ runner.os }}-turbo-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
      - run: pnpm docker
