name: CI

env:
  TURBO_VERSION: 1.2.14
  PNPM_VERSION: 7.1.6

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  lint-test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install pnpm
        run: npm i -g pnpm@${PNPM_VERSION}

      - id: get-store-path
        run: echo ::set-output name=STORE_PATH::$(pnpm store path)

      - uses: actions/cache@v3
        id: cache-pnpm-store
        with:
          path: ${{ steps.get-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
            pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Use `main` Turbo Cache
        if: github.ref != 'refs/heads/main'
        id: turbo-cache-get
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.event.pull_request.base.sha }}
      
      - name: Update Turbo Cache
        if: github.ref == 'refs/heads/main'
        id: turbo-cache-set
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.sha }}
            
      - name: Lint, Test, Build
        run: pnpm ci

      - name: Build deployment images
        if: github.ref != 'refs/heads/main'
        run: pnpm docker
      