name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Download turbo cache
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if artifact is from a different repo
          # Required, if repo is private a Personal Access Token with `repo` scope is needed
#          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: ci.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
#          workflow_conclusion: success
          # Optional, will get head commit SHA
#          pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
#          commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the branch
#          branch: master
          # Optional, defaults to all types
#          event: push
          # Optional, will use specified workflow run
#          run_id: 1122334455
          # Optional, run number from the workflow
#          run_number: 34
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: turbo-cache
          # Optional, directory where to extract artifact(s), defaults to current directory
          path: ./node_modules/.cache/turbo
          # Optional, defaults to current repo
#          repo: ${{github.repository}}
          # Optional, check the workflow run whether it has an artifact
          # then will get the last available artifact from previous workflow
          # default false, just try to download from the last one
          check_artifacts: false
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: false
          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          skip_unpack: false

      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
      
      - name: Archive turbo cache
#        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: turbo-cache
          path: ./node_modules/.cache/turbo
          retention-days: 5
      # - run: pnpm docker


# if main, set turbo as artifact
# if branch/pr download turbo as artifact?
