name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  TURBO_CACHE_KEY: ubuntu-latest-16 # reuse cache key from ci workflow
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: jchilders

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"
          token: ${{ secrets.GPR_TOKEN }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm turbo run build --output-logs=new-only
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm turbo run release --output-logs=new-only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
